apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: staging

images:
  - name: ghcr.io/OWNER/REPO
    newName: ghcr.io/OWNER/REPO
    newTag: latest
