apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app.yaml

commonLabels:
  app.kubernetes.io/name: myapp
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/OWNER/REPO
    newName: ghcr.io/OWNER/REPO
    newTag: latest
