#!/usr/bin/env bash
# Plug-and-play AWS bootstrap: prepares config files and runs Terraform for staging and/or prod.
set -euo pipefail

# --- Defaults (override with environment variables) ---
ENVIRONMENT="${ENVIRONMENT:-staging}"          # staging | prod | both
AWS_REGION="${AWS_REGION:-us-east-1}"
TF_STATE_BUCKET="${TF_STATE_BUCKET:-}"         # required for remote state
TF_LOCK_TABLE="${TF_LOCK_TABLE:-}"           # required for state locking
GITOPS_REPO_URL="${GITOPS_REPO_URL:-https://github.com/panagiod/infra}"
GITOPS_REVISION="${GITOPS_REVISION:-main}"
CREATE_STATE="${CREATE_STATE:-false}"          # true = create S3 bucket + DynamoDB table
SKIP_APPLY="${SKIP_APPLY:-false}"              # true = only copy configs and init

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_ENVS_DIR="${REPO_ROOT}/terraform/environments"

log() { printf '\n==> %s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

# Check local tools before touching AWS
check_prerequisites() {
  log "Checking prerequisites"
  require_cmd terraform
  require_cmd aws
  require_cmd kubectl
  aws sts get-caller-identity >/dev/null || die "AWS CLI is not authenticated. Run: aws configure"
}

# One-time remote state bucket and lock table (optional)
create_remote_state() {
  [[ "${CREATE_STATE}" == "true" ]] || return 0
  [[ -n "${TF_STATE_BUCKET}" ]] || die "TF_STATE_BUCKET is required when CREATE_STATE=true"
  [[ -n "${TF_LOCK_TABLE}" ]] || die "TF_LOCK_TABLE is required when CREATE_STATE=true"

  log "Creating remote state bucket: ${TF_STATE_BUCKET}"
  if aws s3api head-bucket --bucket "${TF_STATE_BUCKET}" 2>/dev/null; then
    log "Bucket already exists"
  else
    if [[ "${AWS_REGION}" == "us-east-1" ]]; then
      aws s3api create-bucket --bucket "${TF_STATE_BUCKET}" --region "${AWS_REGION}"
    else
      aws s3api create-bucket \
        --bucket "${TF_STATE_BUCKET}" \
        --region "${AWS_REGION}" \
        --create-bucket-configuration "LocationConstraint=${AWS_REGION}"
    fi
  fi

  aws s3api put-bucket-versioning \
    --bucket "${TF_STATE_BUCKET}" \
    --versioning-configuration Status=Enabled

  log "Creating DynamoDB lock table: ${TF_LOCK_TABLE}"
  if aws dynamodb describe-table --table-name "${TF_LOCK_TABLE}" --region "${AWS_REGION}" >/dev/null 2>&1; then
    log "Lock table already exists"
  else
    aws dynamodb create-table \
      --table-name "${TF_LOCK_TABLE}" \
      --attribute-definitions AttributeName=LockID,AttributeType=S \
      --key-schema AttributeName=LockID,KeyType=HASH \
      --billing-mode PAY_PER_REQUEST \
      --region "${AWS_REGION}"
  fi
}

# Write backend.hcl and terraform.tfvars from examples for one environment
prepare_env() {
  local env="$1"
  local env_dir="${TF_ENVS_DIR}/${env}"
  local cluster_name="infra-${env}"

  log "Preparing ${env} configuration in ${env_dir}"

  [[ -d "${env_dir}" ]] || die "Unknown environment directory: ${env_dir}"

  if [[ ! -f "${env_dir}/backend.hcl" ]]; then
    [[ -n "${TF_STATE_BUCKET}" ]] || die "Set TF_STATE_BUCKET before bootstrap"
    [[ -n "${TF_LOCK_TABLE}" ]] || die "Set TF_LOCK_TABLE before bootstrap"

    cat >"${env_dir}/backend.hcl" <<EOF
# Generated by scripts/bootstrap-aws.sh — S3 backend for Terraform state
bucket         = "${TF_STATE_BUCKET}"
key            = "infra/${env}/terraform.tfstate"
region         = "${AWS_REGION}"
dynamodb_table = "${TF_LOCK_TABLE}"
encrypt        = true
EOF
  else
    log "backend.hcl already exists — leaving unchanged"
  fi

  if [[ ! -f "${env_dir}/terraform.tfvars" ]]; then
    cp "${env_dir}/terraform.tfvars.example" "${env_dir}/terraform.tfvars"
    # Replace placeholders with bootstrap values (line-targeted to avoid broad sed matches)
    sed -i "s|^aws_region = .*|aws_region = \"${AWS_REGION}\"|" "${env_dir}/terraform.tfvars"
    sed -i "s|^cluster_name = .*|cluster_name = \"${cluster_name}\"|" "${env_dir}/terraform.tfvars"
    sed -i "s|^gitops_repo_url = .*|gitops_repo_url = \"${GITOPS_REPO_URL}\"|" "${env_dir}/terraform.tfvars"
    sed -i "s|^gitops_target_revision = .*|gitops_target_revision = \"${GITOPS_REVISION}\"|" "${env_dir}/terraform.tfvars"
  else
    log "terraform.tfvars already exists — leaving unchanged"
  fi
}

# Run phased Terraform apply: cluster first, then full stack including Argo CD
apply_env() {
  local env="$1"
  local env_dir="${TF_ENVS_DIR}/${env}"

  log "Terraform init (${env})"
  (cd "${env_dir}" && terraform init -backend-config=backend.hcl)

  log "Phase 1: VPC + EKS (${env})"
  (cd "${env_dir}" && terraform apply -auto-approve -target=module.vpc -target=module.eks)

  log "Phase 2: full stack (${env})"
  (cd "${env_dir}" && terraform apply -auto-approve)

  local cluster_name
  cluster_name="$(cd "${env_dir}" && terraform output -raw cluster_name)"
  log "Configure kubectl for ${cluster_name}"
  aws eks update-kubeconfig --region "${AWS_REGION}" --name "${cluster_name}"

  log "Cluster nodes:"
  kubectl get nodes
  log "Argo CD applications (may take a few minutes to sync):"
  kubectl -n argocd get applications 2>/dev/null || log "Argo CD not ready yet — check again shortly"
}

main() {
  check_prerequisites
  create_remote_state

  case "${ENVIRONMENT}" in
    staging|prod)
      prepare_env "${ENVIRONMENT}"
      if [[ "${SKIP_APPLY}" != "true" ]]; then
        apply_env "${ENVIRONMENT}"
      fi
      ;;
    both)
      prepare_env staging
      prepare_env prod
      if [[ "${SKIP_APPLY}" != "true" ]]; then
        apply_env staging
        apply_env prod
      fi
      ;;
    *)
      die "ENVIRONMENT must be staging, prod, or both"
      ;;
  esac

  log "Done. See docs/verify.md and docs/getting-started.md."
}

main "$@"
