#!/usr/bin/env bash
# Plug-and-play Azure bootstrap: prepares config files and runs Terraform for staging and/or prod.
set -euo pipefail

# --- Defaults (override with environment variables) ---
ENVIRONMENT="${ENVIRONMENT:-staging}"          # staging | prod | both
AZURE_REGION="${AZURE_REGION:-westeurope}"
TF_STATE_RG="${TF_STATE_RG:-}"                   # resource group holding remote state
TF_STATE_STORAGE_ACCOUNT="${TF_STATE_STORAGE_ACCOUNT:-}" # storage account for Terraform state
TF_STATE_CONTAINER="${TF_STATE_CONTAINER:-tfstate}"
GITOPS_REPO_URL="${GITOPS_REPO_URL:-https://github.com/panagiod/infra}"
GITOPS_REVISION="${GITOPS_REVISION:-main}"
CREATE_STATE="${CREATE_STATE:-false}"          # true = create storage account + container
SKIP_APPLY="${SKIP_APPLY:-false}"              # true = only copy configs and init

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_ENVS_DIR="${REPO_ROOT}/terraform/environments/azure"

log() { printf '\n==> %s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

# Check local tools before touching Azure
check_prerequisites() {
  log "Checking prerequisites"
  require_cmd terraform
  require_cmd az
  require_cmd kubectl
  az account show >/dev/null || die "Azure CLI is not authenticated. Run: az login"
}

# One-time remote state storage account and blob container (optional)
create_remote_state() {
  [[ "${CREATE_STATE}" == "true" ]] || return 0
  [[ -n "${TF_STATE_RG}" ]] || die "TF_STATE_RG is required when CREATE_STATE=true"
  [[ -n "${TF_STATE_STORAGE_ACCOUNT}" ]] || die "TF_STATE_STORAGE_ACCOUNT is required when CREATE_STATE=true"

  log "Ensuring resource group for remote state: ${TF_STATE_RG}"
  if az group show --name "${TF_STATE_RG}" >/dev/null 2>&1; then
    log "Resource group already exists"
  else
    az group create --name "${TF_STATE_RG}" --location "${AZURE_REGION}" >/dev/null
  fi

  log "Ensuring storage account: ${TF_STATE_STORAGE_ACCOUNT}"
  if az storage account show --name "${TF_STATE_STORAGE_ACCOUNT}" --resource-group "${TF_STATE_RG}" >/dev/null 2>&1; then
    log "Storage account already exists"
  else
    az storage account create \
      --name "${TF_STATE_STORAGE_ACCOUNT}" \
      --resource-group "${TF_STATE_RG}" \
      --location "${AZURE_REGION}" \
      --sku Standard_LRS \
      --encryption-services blob \
      --min-tls-version TLS1_2 \
      >/dev/null
  fi

  local account_key
  account_key="$(az storage account keys list \
    --resource-group "${TF_STATE_RG}" \
    --account-name "${TF_STATE_STORAGE_ACCOUNT}" \
    --query '[0].value' -o tsv)"

  log "Ensuring blob container: ${TF_STATE_CONTAINER}"
  if az storage container show \
    --name "${TF_STATE_CONTAINER}" \
    --account-name "${TF_STATE_STORAGE_ACCOUNT}" \
    --account-key "${account_key}" >/dev/null 2>&1; then
    log "Container already exists"
  else
    az storage container create \
      --name "${TF_STATE_CONTAINER}" \
      --account-name "${TF_STATE_STORAGE_ACCOUNT}" \
      --account-key "${account_key}" \
      >/dev/null
  fi
}

# Write backend.hcl and terraform.tfvars from examples for one environment
prepare_env() {
  local env="$1"
  local env_dir="${TF_ENVS_DIR}/${env}"
  local cluster_name="infra-${env}-aks"
  local resource_group="infra-${env}-rg"

  log "Preparing ${env} configuration in ${env_dir}"

  [[ -d "${env_dir}" ]] || die "Unknown environment directory: ${env_dir}"

  if [[ ! -f "${env_dir}/backend.hcl" ]]; then
    [[ -n "${TF_STATE_RG}" ]] || die "Set TF_STATE_RG before bootstrap"
    [[ -n "${TF_STATE_STORAGE_ACCOUNT}" ]] || die "Set TF_STATE_STORAGE_ACCOUNT before bootstrap"

    cat >"${env_dir}/backend.hcl" <<EOF
# Generated by scripts/bootstrap-azure.sh — Azure Storage backend for Terraform state
resource_group_name  = "${TF_STATE_RG}"
storage_account_name = "${TF_STATE_STORAGE_ACCOUNT}"
container_name       = "${TF_STATE_CONTAINER}"
key                  = "infra/azure/${env}/terraform.tfstate"
EOF
  else
    log "backend.hcl already exists — leaving unchanged"
  fi

  if [[ ! -f "${env_dir}/terraform.tfvars" ]]; then
    cp "${env_dir}/terraform.tfvars.example" "${env_dir}/terraform.tfvars"
    sed -i "s|^azure_region = .*|azure_region = \"${AZURE_REGION}\"|" "${env_dir}/terraform.tfvars"
    sed -i "s|^resource_group_name = .*|resource_group_name = \"${resource_group}\"|" "${env_dir}/terraform.tfvars"
    sed -i "s|^cluster_name = .*|cluster_name = \"${cluster_name}\"|" "${env_dir}/terraform.tfvars"
    sed -i "s|^gitops_repo_url = .*|gitops_repo_url = \"${GITOPS_REPO_URL}\"|" "${env_dir}/terraform.tfvars"
    sed -i "s|^gitops_target_revision = .*|gitops_target_revision = \"${GITOPS_REVISION}\"|" "${env_dir}/terraform.tfvars"
  else
    log "terraform.tfvars already exists — leaving unchanged"
  fi
}

# Run phased Terraform apply: cluster first, then full stack including Argo CD
apply_env() {
  local env="$1"
  local env_dir="${TF_ENVS_DIR}/${env}"

  log "Terraform init (${env})"
  (cd "${env_dir}" && terraform init -backend-config=backend.hcl)

  log "Phase 1: VNet + AKS (${env})"
  (cd "${env_dir}" && terraform apply -auto-approve -target=module.vnet -target=module.aks)

  log "Phase 2: full stack (${env})"
  (cd "${env_dir}" && terraform apply -auto-approve)

  local cluster_name resource_group
  cluster_name="$(cd "${env_dir}" && terraform output -raw cluster_name)"
  resource_group="$(cd "${env_dir}" && terraform output -raw resource_group_name)"
  log "Configure kubectl for ${cluster_name}"
  az aks get-credentials --resource-group "${resource_group}" --name "${cluster_name}" --overwrite-existing

  log "Cluster nodes:"
  kubectl get nodes
  log "Argo CD applications (may take a few minutes to sync):"
  kubectl -n argocd get applications 2>/dev/null || log "Argo CD not ready yet — check again shortly"
}

main() {
  check_prerequisites
  create_remote_state

  case "${ENVIRONMENT}" in
    staging|prod)
      prepare_env "${ENVIRONMENT}"
      if [[ "${SKIP_APPLY}" != "true" ]]; then
        apply_env "${ENVIRONMENT}"
      fi
      ;;
    both)
      prepare_env staging
      prepare_env prod
      if [[ "${SKIP_APPLY}" != "true" ]]; then
        apply_env staging
        apply_env prod
      fi
      ;;
    *)
      die "ENVIRONMENT must be staging, prod, or both"
      ;;
  esac

  log "Done. See docs/azure.md for verification steps."
}

main "$@"
